### ISSUE TITLE
KeyError: 'socketio'

### ISSUE THREAD

**Issue by vinces1979** [abourget/pyramid_socketio#12]
Upgraded pyramid_socketio and I am getting this KeyError:

Traceback (most recent call last):
  File "/home/user/project/socketio/controllers/root.py", line 17, in handler
    retval = socketio_manage(MyController(request))
  File "/home/user/env/lib/python2.7/site-packages/pyramid_socketio/io.py", line 54, in **init**
    self.io = request.environ['socketio']
KeyError: 'socketio'

Any suggestions?

**Comment by rennat** [comment]
ditto getting the same

**Comment by vinces1979** [comment]
I moved to using gevent-socketio for now

**Comment by abourget** [comment]
Right, most of the logic that was in pyramid_socketio is now directly in gevent-socketio .. so pyramid_socketio will soon be deprecated.   Moreover, the integration required for gevent-socketio is so minimal, that it barely needs a package to tie both together.

**Comment by abourget** [comment]
gevent-socketio has been improved great at PyCon 2012.  Use it instead :)

**Comment by rennat** [comment]
thank you for the update! i wish I had made it to PyCon.
On Apr 3, 2012 9:10 AM, "Alexandre Bourget" <
reply@reply.github.com>
wrote:

**Comment by craigdub** [comment]
I moved to straight gevent-socketio and am still getting the same error any suggestions?

**Comment by abourget** [comment]
That would mean that you are not using pyramid_socketio anymore ?

The 'socketio' key will be found on the 'environ' of the request.  I've updated the docs for socketio_manage(), you might want to have a look at it:

  48    NOTE: You must understand that this function is going to be called  
  49    _only once_ per socket opening, _even though_ you are using a long  
  50    polling mechanism.  The subsequent calls (for long polling) will  
  51    be hooked directly at the server-level, to interact with the  
  52    active `Socket` instance.  This means you will _not_ get access  
  53    to the future `request` or `environ` objects.  This is of  
  54    particular importance regarding sessions (like Beaker).  The  
  55    session will be opened once at the opening of the Socket, and not  
  56    closed until the socket is closed.  You are responsible for  
  57    opening and closing the cookie-based session yourself if you want  
  58    to keep its data in sync with the rest of your GET/POST calls.

**Comment by abourget** [comment]
Otherwise, maybe you want to paste a chunk of code for us to look at ?

**Comment by aaguirre** [comment]
If somebody else came from google to this page with the same problem, this is because the socket.io file in CDN (http://cdn.socket.io/stable/socket.io.js) is outdated. Replace this with a newest one, stored locally and will work. I lost my morning on this :)

BTW, gevent-socketio is just great..

**Comment by creotiv** [comment]
Have the same problem (using socket.io.js v0.9.6)
